# Generated by Django 5.1.7 on 2025-03-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
