# Generated by Django 5.1.7 on 2025-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('voided', 'Voided')], default='draft', max_length=10),
        ),
    ]
