# Generated by Django 5.1.7 on 2025-03-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='posted',
        ),
    ]
